# Dapr Secret Store Component for Kubernetes
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secret-store
  namespace: learnflow
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: namespaces
    value: [learnflow, postgres]
