apiVersion: v1
kind: Service
metadata:
  name: learnflow-frontend-lb
  namespace: learnflow
spec:
  type: LoadBalancer
  selector:
    app: learnflow-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
