apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learnflow-ingress
  namespace: learnflow
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  # Frontend - catch all
  - host: learnflow.144.126.252.229.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: learnflow-frontend
            port:
              number: 3000
